### ISSUE TITLE
Adding an item should include some school id

### ISSUE THREAD

**Issue by Daanra** [RUGSoftEng/2017-Winter-Summer-School-App#139]
Currently when you add a new annoucement a schoolid is inserted for that school. This is not yet true for general information, calendar events and the forum. Since we do not have a user interface for the forum on the webinterface, nothing should be changed here (apart from the API). The general information and calendar events, however, should be inserted to the database along with the school id of the coordinator that is logged in.

**Comment by Micrified** [comment]
Just wanted to mention that the legacy calendar was implemented with a school id attribute for calendar events. However, it's just a string defined in the form used for adding calendar events and would need to be reworked since you're overhauling the database.
